import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-auto`}
      >
        <div className="relative min-h-screen overflow-hidden">
          {/* Blurred spheres */}
          <div className="absolute inset-0 overflow-x-hidden pointer-events-none">
            <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] rounded-full bg-green-500 opacity-30 blur-[100px]" />
            <div className="absolute top-[-30%] right-[-10%] w-[60%] h-[60%] rounded-full bg-purple-500 opacity-30 blur-[100px]" />
            {/* <div className="absolute top-[30%] right-[-5%] w-[40%] h-[40%] rounded-full bg-orange-300 opacity-30 blur-[100px]" /> */}
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
